import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import Rpg from "App/Models/Rpg";

export default class extends BaseSeeder {
  public async run() {
    await Rpg.createMany([
      {
        nomePersonagem: "Guts",
        nomeJogador: "Hugo",
        raca: "Humano",
        classe: "Barbaro",
        antecedente: "Mercenario",
        nivel: 5,
        alinhamento: "Caothic Good",
        forca: 18,
        destreza: 16,
        constituicao: 16,
        inteligencia: 8,
        sabedoria: 10,
        carisma: 16,
        nascimento: new Date(2002, 2, 12),
      },
      {
        nomePersonagem: "Seelah",
        nomeJogador: "Joao",
        raca: "Humano",
        classe: "Paladino",
        antecedente: "Cristao",
        nivel: 9,
        alinhamento: "Lawfull Good",
        forca: 14,
        destreza: 12,
        constituicao: 18,
        inteligencia: 10,
        sabedoria: 14,
        carisma: 8,
        nascimento: new Date(2005, 8, 30),
      },
      {
        nomePersonagem: "Mordekai",
        nomeJogador: "Diogo",
        raca: "Tiefiling",
        classe: "Rogue",
        antecedente: "Ladrao",
        nivel: 8,
        alinhamento: "Caothic Mal",
        forca: 10,
        destreza: 18,
        constituicao: 12,
        inteligencia: 12,
        sabedoria: 8,
        carisma: 16,
        nascimento: new Date(2009, 5, 8),
      },
      {
        nomePersonagem: "Grifith",
        nomeJogador: "Marcos",
        raca: "Orc",
        classe: "Mago",
        antecedente: "academico",
        nivel: 3,
        alinhamento: "Lawfull Neutral",
        forca: 10,
        destreza: 14,
        constituicao: 12,
        inteligencia: 18,
        sabedoria: 16,
        carisma: 12,
        nascimento: new Date(2007, 7, 1),
      },
      {
        nomePersonagem: "Osten",
        nomeJogador: "Renato",
        raca: "elf",
        classe: "Guerreiro",
        antecedente: "estudante",
        nivel: 1,
        alinhamento: "Neutral",
        forca: 18,
        destreza: 16,
        constituicao: 16,
        inteligencia: 8,
        sabedoria: 10,
        carisma: 16,
        nascimento: new Date(2000, 12, 12),
      },
    ]);
    // Write your database queries inside the run method
  }
}
